apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: adminpassword
  MYSQL_DATABASE: innovatech_db
  MYSQL_USER: admin
  MYSQL_PASSWORD: adminpassword