apiVersion: apps/v1
kind: Deployment
metadata:
  name: ventas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ventas
  template:
    metadata:
      labels:
        app: ventas
    spec:
      containers:
      - name: ventas
        image: 341863303538.dkr.ecr.us-east-1.amazonaws.com/innovatech-ventas:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-service:3306/innovatech_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
        - name: SPRING_DATASOURCE_USERNAME
          value: admin
        - name: SPRING_DATASOURCE_PASSWORD
          value: adminpassword