name: CI/CD Innovatech Backend

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  ECR_REPO_VENTAS: eksventas
  ECR_REPO_DESPACHOS: eksdespacho

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Definir TAG
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build Ventas
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          cd back-Ventas_SpringBoot/Springboot-API-REST
          docker build -t $ECR_REGISTRY/${ECR_REPO_VENTAS}:${IMAGE_TAG} .
          docker push $ECR_REGISTRY/${ECR_REPO_VENTAS}:${IMAGE_TAG}

      - name: Build Despachos
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          cd back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
          docker build -t $ECR_REGISTRY/${ECR_REPO_DESPACHOS}:${IMAGE_TAG} .
          docker push $ECR_REGISTRY/${ECR_REPO_DESPACHOS}:${IMAGE_TAG}

      - uses: azure/setup-kubectl@v4
        with:
          version: v1.29.0

      - name: Configurar EKS
        run: |
          aws eks update-kubeconfig \
          --region ${{ secrets.AWS_REGION }} \
          --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Aplicar recursos MySQL
        run: |
          kubectl apply -f k8s/mysql-secret.yaml
          kubectl apply -f k8s/mysql-deployment.yaml
          kubectl apply -f k8s/mysql-service.yaml

      - name: Deploy Ventas
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          kubectl apply -f k8s/ventas-deployment.yaml
          kubectl apply -f k8s/ventas-service.yaml

          kubectl set image deployment/ventas \
          ventas=$ECR_REGISTRY/${ECR_REPO_VENTAS}:${IMAGE_TAG}

          kubectl rollout status deployment/ventas

      - name: Deploy Despachos
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          kubectl apply -f k8s/despachos-deployment.yaml
          kubectl apply -f k8s/despachos-service.yaml

          kubectl set image deployment/despachos \
          despachos=$ECR_REGISTRY/${ECR_REPO_DESPACHOS}:${IMAGE_TAG}

          kubectl rollout status deployment/despachos

      - name: HPA
        run: |
          kubectl apply -f k8s/hpa.yaml

      - name: Estado Final
        run: |
          kubectl get pods
          kubectl get svc
          kubectl get hpa

